/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai-task-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Settings */
        get: operations["_list_settings_api_ai_task_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-task-settings/{task_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Setting */
        put: operations["_update_setting_api_ai_task_settings__task_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/app/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["_shutdown_api_app_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Character Assets */
        get: operations["_list_character_assets_api_assets_characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/characters/{role_name}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Default Portrait */
        get: operations["_get_default_portrait_api_assets_characters__role_name__default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Maps */
        get: operations["_list_maps_api_assets_maps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/maps/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Map */
        get: operations["_get_map_api_assets_maps__scene_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["_get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["_list_models_api_models_get"];
        put?: never;
        /** Create Model */
        post: operations["_create_model_api_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["_get_model_api_models__model_id__get"];
        put?: never;
        post?: never;
        /** Delete Model */
        delete: operations["_delete_model_api_models__model_id__delete"];
        options?: never;
        head?: never;
        /** Update Model */
        patch: operations["_update_model_api_models__model_id__patch"];
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["_list_providers_api_providers_get"];
        put?: never;
        /** Create Provider */
        post: operations["_create_provider_api_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider */
        get: operations["_get_provider_api_providers__provider_id__get"];
        put?: never;
        post?: never;
        /** Delete Provider */
        delete: operations["_delete_provider_api_providers__provider_id__delete"];
        options?: never;
        head?: never;
        /** Update Provider */
        patch: operations["_update_provider_api_providers__provider_id__patch"];
        trace?: never;
    };
    "/api/providers/{provider_id}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider Connection */
        post: operations["_test_provider_connection_api_providers__provider_id__test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_roles_get"];
        put?: never;
        /** Create Role */
        post: operations["create_role_api_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Role */
        get: operations["get_role_api_roles__role_id__get"];
        put?: never;
        post?: never;
        /** Delete Role */
        delete: operations["delete_role_api_roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update Role */
        patch: operations["update_role_api_roles__role_id__patch"];
        trace?: never;
    };
    "/api/turn-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_turn_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turn-runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_turn_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turn-runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_turn_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Worlds */
        get: operations["list_worlds_api_worlds_get"];
        put?: never;
        /** Create World */
        post: operations["create_world_api_worlds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete World */
        delete: operations["delete_world_api_worlds__world_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}/game-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game View */
        get: operations["get_game_view_api_worlds__world_id__game_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Location */
        post: operations["select_location_api_worlds__world_id__location_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List World Roles */
        get: operations["list_world_roles_api_worlds__world_id__roles_get"];
        put?: never;
        /** Add World Role */
        post: operations["add_world_role_api_worlds__world_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove World Role */
        delete: operations["remove_world_role_api_worlds__world_id__roles__role_id__delete"];
        options?: never;
        head?: never;
        /** Update World Role */
        patch: operations["update_world_role_api_worlds__world_id__roles__role_id__patch"];
        trace?: never;
    };
    "/api/worlds/{world_id}/roles/{role_id}/effective-attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Effective Attributes */
        get: operations["read_effective_attributes_api_worlds__world_id__roles__role_id__effective_attributes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}/roles/{role_id}/location-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Location Rules */
        put: operations["replace_location_rules_api_worlds__world_id__roles__role_id__location_rules_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}/turn-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_worlds__world_id__turn_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/worlds/{world_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Turns */
        get: operations["list_turns_api_worlds__world_id__turns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AiErrorCategory
         * @enum {string}
         */
        AiErrorCategory: "invalid_request" | "authentication" | "permission" | "insufficient_balance" | "rate_limited" | "timeout" | "network" | "unavailable" | "invalid_response" | "cancelled";
        /**
         * AttributeDefinition
         * @description 角色主表拥有的单个平铺属性定义。
         */
        AttributeDefinition: {
            /** Allowed Operations */
            allowed_operations: ("replace" | "increment" | "decrement")[];
            /** Base Value */
            base_value: number | string | boolean;
            /**
             * Data Type
             * @enum {string}
             */
            data_type: "integer" | "number" | "string" | "boolean" | "enum";
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /**
             * Enum Options
             * @default []
             */
            enum_options: string[];
            /** Key */
            key: string;
            /** Maximum */
            maximum?: number | null;
            /** Minimum */
            minimum?: number | null;
            /** No Update Example */
            no_update_example?: string | null;
            /** Update Example */
            update_example?: string | null;
            /** Update Rule */
            update_rule: string;
        };
        /** CharacterAssetResponse */
        CharacterAssetResponse: {
            /** Portrait Url */
            portrait_url: string;
            /** Role Name */
            role_name: string;
        };
        /** ConnectionTestRequest */
        ConnectionTestRequest: {
            /** Model Id */
            model_id: number;
        };
        /** ConnectionTestResponse */
        ConnectionTestResponse: {
            /** Capabilities */
            capabilities: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Diagnostic */
            diagnostic: string;
            error_category: components["schemas"]["AiErrorCategory"] | null;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "openai_compatible" | "deepseek";
            /** Remote Model */
            remote_model: string;
            /** Success */
            success: boolean;
            usage: components["schemas"]["TokenUsage"] | null;
        };
        /** EffectiveAttributesResponse */
        EffectiveAttributesResponse: {
            /** Role Id */
            role_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Values */
            values: {
                [key: string]: number | string | boolean;
            };
            /** World Id */
            world_id: number;
        };
        /** GameViewResponse */
        GameViewResponse: {
            /** Background Url */
            background_url: string;
            /** Day */
            day: number;
            /** Fallback Background Url */
            fallback_background_url: string;
            /** Locations */
            locations: components["schemas"]["MapLocationResponse"][];
            /** Player Location Id */
            player_location_id: string;
            /** Player Marker Url */
            player_marker_url: string;
            /** Scene Id */
            scene_id: string;
            /** Time Slot */
            time_slot: string;
            /** Visible Roles */
            visible_roles: components["schemas"]["WorldRoleResponse"][];
            /** Weekday */
            weekday: string;
            /** World Id */
            world_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Version */
            app_version: string;
            /**
             * Database
             * @constant
             */
            database: "ok";
            /** Sqlite Version */
            sqlite_version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        JsonValue: unknown;
        /** LocationCandidateCreate */
        LocationCandidateCreate: {
            /**
             * Location Id
             * @enum {string}
             */
            location_id: "the_home" | "the_dungeon" | "the_mall" | "the_guild" | "the_hotel" | "the_school";
            /** Weight */
            weight: number;
        };
        /** LocationRuleCreate */
        LocationRuleCreate: {
            /** Candidates */
            candidates: components["schemas"]["LocationCandidateCreate"][];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "fixed" | "random";
            /** Priority */
            priority: number;
            /**
             * Time Slot
             * @enum {string}
             */
            time_slot: "morning" | "midday" | "evening" | "night";
            /** Weekday Mask */
            weekday_mask: number;
        };
        /** LocationRuleResponse */
        LocationRuleResponse: {
            /** Candidates */
            candidates: components["schemas"]["LocationCandidateCreate"][];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: number;
            /**
             * Mode
             * @enum {string}
             */
            mode: "fixed" | "random";
            /** Priority */
            priority: number;
            /** Role Id */
            role_id: number;
            /**
             * Time Slot
             * @enum {string}
             */
            time_slot: "morning" | "midday" | "evening" | "night";
            /** Weekday Mask */
            weekday_mask: number;
            /** World Id */
            world_id: number;
        };
        /** LocationSelection */
        LocationSelection: {
            /**
             * Location Id
             * @enum {string}
             */
            location_id: "the_home" | "the_dungeon" | "the_mall" | "the_guild" | "the_hotel" | "the_school";
        };
        /** MapAnchorResponse */
        MapAnchorResponse: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** MapAssetResponse */
        MapAssetResponse: {
            anchor: components["schemas"]["MapAnchorResponse"] | null;
            /** Display Name */
            display_name: string;
            /** Fallback Image Url */
            fallback_image_url: string;
            /** Image Url */
            image_url: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "the_world_map" | "location";
            /** Order */
            order: number;
            /** Scene Id */
            scene_id: string;
        };
        /** MapCatalogResponse */
        MapCatalogResponse: {
            /** Scenes */
            scenes: components["schemas"]["MapAssetResponse"][];
            /** Version */
            version: number;
        };
        /** MapLocationResponse */
        MapLocationResponse: {
            /** Anchor X */
            anchor_x: number;
            /** Anchor Y */
            anchor_y: number;
            /** Display Name */
            display_name: string;
            /** Order */
            order: number;
            /**
             * Scene Id
             * @enum {string}
             */
            scene_id: "the_home" | "the_dungeon" | "the_mall" | "the_guild" | "the_hotel" | "the_school";
        };
        /** ModelCreate */
        ModelCreate: {
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Display Name */
            display_name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Provider Id */
            provider_id: number;
            /** Remote Model */
            remote_model: string;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Capabilities */
            capabilities: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Provider Id */
            provider_id: number;
            /** Remote Model */
            remote_model: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ModelUpdate */
        ModelUpdate: {
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Display Name */
            display_name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Provider Id */
            provider_id?: number | null;
            /** Remote Model */
            remote_model?: string | null;
        };
        /**
         * NodeKey
         * @description 固定节点标识不复用配置层的 TaskKey，避免运行进度耦合配置存储。
         * @enum {string}
         */
        NodeKey: "location_simulation" | "attribute_memory_analysis";
        /** ProviderCreate */
        ProviderCreate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Extra */
            extra?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Name */
            name: string;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "openai_compatible" | "deepseek";
        };
        /** ProviderResponse */
        ProviderResponse: {
            /** Base Url */
            base_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Extra */
            extra: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Has Api Key */
            has_api_key: boolean;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "openai_compatible" | "deepseek";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Extra */
            extra?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Name */
            name?: string | null;
            /** Provider Type */
            provider_type?: ("openai_compatible" | "deepseek") | null;
        };
        /** RoleCreate */
        RoleCreate: {
            /** Attributes */
            attributes?: components["schemas"]["AttributeDefinition"][];
            /** Name */
            name: string;
            /** Persona */
            persona: string;
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /**
             * World Book
             * @default
             */
            world_book: string;
        };
        /** RoleResponse */
        RoleResponse: {
            /** Attributes */
            attributes: components["schemas"]["AttributeDefinition"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Effective Base Values */
            effective_base_values: {
                [key: string]: number | string | boolean;
            };
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Persona */
            persona: string;
            /** Portrait Url */
            portrait_url: string;
            /** Referenced World Ids */
            referenced_world_ids: number[];
            /** System Prompt */
            system_prompt: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** World Book */
            world_book: string;
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Attributes */
            attributes?: components["schemas"]["AttributeDefinition"][] | null;
            /** Persona */
            persona?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** World Book */
            world_book?: string | null;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "succeeded" | "failed" | "cancelled";
        /** ShutdownResponse */
        ShutdownResponse: {
            /**
             * Status
             * @constant
             */
            status: "shutting_down";
        };
        /** StateChangeResponse */
        StateChangeResponse: {
            /** Attribute Key */
            attribute_key: string;
            new_value: components["schemas"]["JsonValue"];
            old_value: components["schemas"]["JsonValue"];
            operand: components["schemas"]["JsonValue"];
            /** Operation */
            operation: string;
            /** Reason */
            reason: string;
            /** Role Id */
            role_id: number;
        };
        /**
         * StructuredOutputMode
         * @enum {string}
         */
        StructuredOutputMode: "auto" | "native" | "prompt";
        /**
         * TaskKey
         * @enum {string}
         */
        TaskKey: "location_simulation" | "attribute_memory_analysis";
        /** TaskSettingResponse */
        TaskSettingResponse: {
            /** Extra Prompt */
            extra_prompt: string;
            /** Max Output Tokens */
            max_output_tokens: number | null;
            /** Memory Max Chars */
            memory_max_chars: number | null;
            /** Memory Target Chars */
            memory_target_chars: number | null;
            /** Model Id */
            model_id: number | null;
            /** Provider Options */
            provider_options: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Reasoning Effort */
            reasoning_effort: ("high" | "max") | null;
            structured_output_mode: components["schemas"]["StructuredOutputMode"];
            task_key: components["schemas"]["TaskKey"];
            /** Temperature */
            temperature: number | null;
            /** Timeout Seconds */
            timeout_seconds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * TaskSettingUpdate
         * @description 保存一个固定任务时由 API 和 Service 共用的受控值对象。
         */
        TaskSettingUpdate: {
            /** Extra Prompt */
            extra_prompt: string;
            /** Max Output Tokens */
            max_output_tokens: number | null;
            /** Memory Max Chars */
            memory_max_chars: number | null;
            /** Memory Target Chars */
            memory_target_chars: number | null;
            /** Model Id */
            model_id: number | null;
            /** Provider Options */
            provider_options: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Reasoning Effort */
            reasoning_effort: ("high" | "max") | null;
            structured_output_mode: components["schemas"]["StructuredOutputMode"];
            /** Temperature */
            temperature: number | null;
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /** TokenUsage */
        TokenUsage: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** @enum {string} */
        TurnEventKind: "node_started" | "node_retrying" | "node_succeeded" | "map_completed" | "node_failed" | "run_succeeded" | "run_failed" | "run_cancelled";
        /** TurnEventResponse */
        TurnEventResponse: {
            /** Event Id */
            event_id: number;
            /** Event Type */
            event_type: string;
            /** Fact */
            fact: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Location Id */
            location_id: string;
        };
        /** TurnResponse */
        TurnResponse: {
            /** Day */
            day: number;
            /** Events */
            events: components["schemas"]["TurnEventResponse"][];
            /** Player Intent */
            player_intent: string;
            /** Roles */
            roles: components["schemas"]["TurnRoleResponse"][];
            /** State Changes */
            state_changes: components["schemas"]["StateChangeResponse"][];
            /** Time Slot */
            time_slot: string;
            /** Turn Id */
            turn_id: number;
        };
        /** TurnRoleResponse */
        TurnRoleResponse: {
            /** Content */
            content: string;
            /** Offline */
            offline: boolean;
            /** Role Id */
            role_id: number;
        };
        /** TurnRunCreate */
        TurnRunCreate: {
            /** Player Intent */
            player_intent: string;
        };
        /** TurnRunCreated */
        TurnRunCreated: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @constant
             */
            status: "pending";
        };
        /** TurnRunEventResponse */
        TurnRunEventResponse: {
            /** Attempt */
            attempt: number | null;
            /** Completed Maps */
            completed_maps: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Error */
            error?: string | null;
            kind: components["schemas"]["TurnEventKind"];
            /** Location Id */
            location_id: string | null;
            /** Max Attempts */
            max_attempts: number;
            node: components["schemas"]["NodeKey"] | null;
            /** Retrying */
            retrying: boolean;
            /** Run Id */
            run_id: string;
            /** Total Maps */
            total_maps: number;
            turn?: components["schemas"]["TurnResponse"] | null;
        };
        /** TurnRunStatusResponse */
        TurnRunStatusResponse: {
            /** Error */
            error?: string | null;
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Turn Id */
            turn_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorldCreate */
        WorldCreate: {
            /** Protagonist Role Id */
            protagonist_role_id: number;
        };
        /** WorldResponse */
        WorldResponse: {
            /** Active Branch Id */
            active_branch_id: number;
            /** Day */
            day: number;
            /** Display Name */
            display_name: string;
            /** Id */
            id: number;
            /**
             * Last Played At
             * Format: date-time
             */
            last_played_at: string;
            /** Npc Count */
            npc_count: number;
            player_role: components["schemas"]["RoleResponse"];
            /** Time Slot */
            time_slot: string;
            /** Weekday */
            weekday: string;
        };
        /** WorldRoleAdd */
        WorldRoleAdd: {
            /** Role Id */
            role_id: number;
        };
        /** WorldRoleEnabledUpdate */
        WorldRoleEnabledUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** WorldRoleResponse */
        WorldRoleResponse: {
            /** Effective Attributes */
            effective_attributes: {
                [key: string]: number | string | boolean;
            };
            /** Enabled */
            enabled: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "player" | "npc";
            /** Name */
            name: string;
            /** Portrait Url */
            portrait_url: string;
            /** Role Id */
            role_id: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            /** World Id */
            world_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _list_settings_api_ai_task_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSettingResponse"][];
                };
            };
        };
    };
    _update_setting_api_ai_task_settings__task_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_key: components["schemas"]["TaskKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskSettingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSettingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _shutdown_api_app_shutdown_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Clear-Sky-Shutdown-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShutdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _list_character_assets_api_assets_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterAssetResponse"][];
                };
            };
        };
    };
    _get_default_portrait_api_assets_characters__role_name__default_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _list_maps_api_assets_maps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapCatalogResponse"];
                };
            };
        };
    };
    _get_map_api_assets_maps__scene_id__get: {
        parameters: {
            query?: {
                default?: boolean;
            };
            header?: never;
            path: {
                scene_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    _list_models_api_models_get: {
        parameters: {
            query?: {
                provider_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _create_model_api_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _get_model_api_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _delete_model_api_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _update_model_api_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"][];
                };
            };
        };
    };
    _create_provider_api_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _get_provider_api_providers__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _delete_provider_api_providers__provider_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _update_provider_api_providers__provider_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _test_provider_connection_api_providers__provider_id__test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"][];
                };
            };
        };
    };
    create_role_api_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_role_api_roles__role_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_role_api_roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_role_api_roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_turn_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnRunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_turn_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnRunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_turn_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 完整 NDJSON 轮次进度事件流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["TurnRunEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_worlds_api_worlds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldResponse"][];
                };
            };
        };
    };
    create_world_api_worlds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorldCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_world_api_worlds__world_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_view_api_worlds__world_id__game_view_get: {
        parameters: {
            query: {
                scene_id: string;
            };
            header?: never;
            path: {
                world_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_location_api_worlds__world_id__location_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_world_roles_api_worlds__world_id__roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldRoleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_world_role_api_worlds__world_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorldRoleAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_world_role_api_worlds__world_id__roles__role_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_world_role_api_worlds__world_id__roles__role_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorldRoleEnabledUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldRoleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_effective_attributes_api_worlds__world_id__roles__role_id__effective_attributes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
                role_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveAttributesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_location_rules_api_worlds__world_id__roles__role_id__location_rules_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
                role_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationRuleCreate"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationRuleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_worlds__world_id__turn_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnRunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_turns_api_worlds__world_id__turns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                world_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
