/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/app/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown */
        post: operations["_shutdown_api_app_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["_get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["_list_models_api_models_get"];
        put?: never;
        /** Create Model */
        post: operations["_create_model_api_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["_get_model_api_models__model_id__get"];
        put?: never;
        post?: never;
        /** Delete Model */
        delete: operations["_delete_model_api_models__model_id__delete"];
        options?: never;
        head?: never;
        /** Update Model */
        patch: operations["_update_model_api_models__model_id__patch"];
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["_list_providers_api_providers_get"];
        put?: never;
        /** Create Provider */
        post: operations["_create_provider_api_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider */
        get: operations["_get_provider_api_providers__provider_id__get"];
        put?: never;
        post?: never;
        /** Delete Provider */
        delete: operations["_delete_provider_api_providers__provider_id__delete"];
        options?: never;
        head?: never;
        /** Update Provider */
        patch: operations["_update_provider_api_providers__provider_id__patch"];
        trace?: never;
    };
    "/api/providers/{provider_id}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider Connection */
        post: operations["_test_provider_connection_api_providers__provider_id__test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AiErrorCategory
         * @enum {string}
         */
        AiErrorCategory: "invalid_request" | "authentication" | "insufficient_balance" | "rate_limited" | "timeout" | "network" | "unavailable" | "invalid_response" | "cancelled";
        /** ConnectionTestRequest */
        ConnectionTestRequest: {
            /** Model Id */
            model_id: number;
        };
        /** ConnectionTestResponse */
        ConnectionTestResponse: {
            /** Capabilities */
            capabilities: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Diagnostic */
            diagnostic: string;
            error_category: components["schemas"]["AiErrorCategory"] | null;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "openai_compatible" | "deepseek";
            /** Remote Model */
            remote_model: string;
            /** Success */
            success: boolean;
            usage: components["schemas"]["TokenUsage"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Version */
            app_version: string;
            /**
             * Database
             * @constant
             */
            database: "ok";
            /** Sqlite Version */
            sqlite_version: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        JsonValue: unknown;
        /** ModelCreate */
        ModelCreate: {
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Defaults */
            defaults?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Display Name */
            display_name: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Provider Id */
            provider_id: number;
            /** Remote Model */
            remote_model: string;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Capabilities */
            capabilities: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Defaults */
            defaults: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: number;
            /** Provider Id */
            provider_id: number;
            /** Remote Model */
            remote_model: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ModelUpdate */
        ModelUpdate: {
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Defaults */
            defaults?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Display Name */
            display_name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Provider Id */
            provider_id?: number | null;
            /** Remote Model */
            remote_model?: string | null;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Extra */
            extra?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Name */
            name: string;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "openai_compatible" | "deepseek";
        };
        /** ProviderResponse */
        ProviderResponse: {
            /** Base Url */
            base_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Extra */
            extra: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Has Api Key */
            has_api_key: boolean;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Provider Type
             * @enum {string}
             */
            provider_type: "openai_compatible" | "deepseek";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Extra */
            extra?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Name */
            name?: string | null;
            /** Provider Type */
            provider_type?: ("openai_compatible" | "deepseek") | null;
        };
        /** ShutdownResponse */
        ShutdownResponse: {
            /**
             * Status
             * @constant
             */
            status: "shutting_down";
        };
        /** TokenUsage */
        TokenUsage: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _shutdown_api_app_shutdown_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Clear-Sky-Shutdown-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShutdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    _list_models_api_models_get: {
        parameters: {
            query?: {
                provider_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _create_model_api_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _get_model_api_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _delete_model_api_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _update_model_api_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"][];
                };
            };
        };
    };
    _create_provider_api_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _get_provider_api_providers__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _delete_provider_api_providers__provider_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _update_provider_api_providers__provider_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _test_provider_connection_api_providers__provider_id__test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
